export const currencyCode = [
  {
    Country: "NewZealand",
    CountryCode: "NZ",
    Currency: "NewZealand Dollars",
    Code: "NZD",
  },
  {
    Country: "Australian",
    CountryCode: "AU",
    Currency: "Australian Dollars",
    Code: "AUD",
  },
  {
    Country: "AmericanSamoa",
    CountryCode: "AS",
    Currency: "Euro",
    Code: "EUR",
  },
  {
    Country: "HongKong",
    CountryCode: "HK",
    Currency: "Hong Kong Doller",
    Code: "HKD",
  },
  {
    Country: "Canada",
    CountryCode: "CA",
    Currency: "Canadian Dollar",
    Code: "CAD",
  },
  {
    Country: "Japan",
    CountryCode: "JP",
    Currency: "Japanese Yen",
    Code: "JPY",
  },
  {
    Country: "Bhutan",
    CountryCode: "BT",
    Currency: "Indian Rupee",
    Code: "INR",
  },
  {
    Country: "BouvetIsland",
    CountryCode: "BV",
    Currency: "Norwegian Krone",
    Code: "NOK",
  },
  {
    Country: "Brazil",
    CountryCode: "BR",
    Currency: "Brazil",
    Code: "BRL",
  },
  {
    Country: "Bulgaria",
    CountryCode: "BG",
    Currency: "Bulgarian Lev",
    Code: "BGN",
  },
  {
    Country: "China",
    CountryCode: "CN",
    Currency: "China Yuan",
    Code: "CNY",
  },
  {
    Country: "Croatia(Hrvatska)",
    CountryCode: "HR",
    Currency: "Croatian Dinar",
    Code: "HRK",
  },
  {
    Country: "CzechRepublic",
    CountryCode: "CZ",
    Currency: "Czech Koruna",
    Code: "CZK",
  },
  {
    Country: "Denmark",
    CountryCode: "DK",
    Currency: "Danish Krone",
    Code: "DKK",
  },
  {
    Country: "EastTimor",
    CountryCode: "TP",
    Currency: "Indonesian Rupiah",
    Code: "IDR",
  },
  {
    Country: "Hungary",
    CountryCode: "HU",
    Currency: "Hungarian Forint",
    Code: "HUF",
  },
  {
    Country: "Iceland",
    CountryCode: "IS",
    Currency: "Icelandic Krona",
    Code: "ISK",
  },
  {
    Country: "Israel",
    CountryCode: "IL",
    Currency: "Israel New Shekel",
    Code: "ILS",
  },
  {
    Country: "Liechtenstein",
    CountryCode: "LI",
    Currency: "Swiss Franc",
    Code: "CHF",
  },
  {
    Country: "Malaysia",
    CountryCode: "MY",
    Currency: "Malaysian Ringgit",
    Code: "MYR",
  },
  {
    Country: "Poland",
    CountryCode: "PL",
    Currency: "Poland Zloty",
    Code: "PLN",
  },
  {
    Country: "RussianFederation",
    CountryCode: "RU",
    Currency: "Russian Ruble",
    Code: "RUB",
  },
  {
    Country: "SouthAfrica",
    CountryCode: "ZA",
    Currency: "South Africa Rand",
    Code: "ZAR",
  },
  {
    Country: "Sweden",
    CountryCode: "SE",
    Currency: "Swedish Krona",
    Code: "SEK",
  },
  {
    Country: "Thailand",
    CountryCode: "TH",
    Currency: "Thai Baht",
    Code: "THB",
  },
  {
    Country: "Turkey",
    CountryCode: "TR",
    Currency: "Turkish Lira",
    Code: "TRY",
  },
  {
    Country: "British",
    CountryCode: "BR",
    Currency: "British Pound",
    Code: "GBP",
  },
  {
    Country: "USArmedForces",
    CountryCode: "USAF",
    Currency: "US Dollar",
    Code: "USD",
  },
];
